# Is a value missing at random, or is the absence itself the signal?
#
# This table is more than a third null in places, and the pipeline already
# treats missingness as informative -- the binning gives it its own bucket. That
# is a modelling choice, and until now an untested one. Little's test makes it a
# claim with a p-value behind it.
#
# The null is MCAR: missing completely at random, meaning the probability a
# value is absent depends on nothing. Rejecting it says the absences carry
# structure. It does *not* say what kind -- MAR and MNAR are not distinguishable
# from the data alone, and no test in R or anywhere else separates them.
#
# References: Little (1988), *JASA* 83(404); Enders (2010), *Applied Missing
# Data Analysis*, ch. 1.3 on why the MAR/MNAR distinction is untestable.

#' Columns present in essentially every row, to test a family's absence against.
#'
#' Little's test compares the means of the *observed* variables across
#' missingness patterns. A family whose columns all vanish together therefore
#' cannot be tested against itself: in the pattern where the family is absent
#' there is nothing left to take a mean of, and the test degenerates.
#'
#' Anchoring on always-observed columns makes the question well posed and turns
#' it into the one worth asking -- when this family is missing, do the things we
#' always see look different? A yes is evidence the absence is tied to the data
#' rather than to chance.
reference_columns <- function(win, features = NULL, max_null = 0.001, limit = 6L) {
  features <- features %||% win$features
  numeric_features <- features[vapply(features, function(f) is.numeric(win$train[[f]]), logical(1))]
  null_share <- vapply(numeric_features, function(f) mean(is.na(win$train[[f]])), numeric(1))
  varying <- vapply(numeric_features, function(f) {
    v <- win$train[[f]]; length(unique(stats::na.omit(v))) > 5L
  }, logical(1))
  candidates <- numeric_features[null_share <= max_null & varying]
  utils::head(candidates, limit)
}

#' Little's MCAR test for one missingness family.
#'
#' Run per family rather than over the whole table: the statistic is built from
#' the distinct missingness patterns, and 472 columns produce so many patterns
#' that the degrees of freedom exceed the rows, leaving the test undefined
#' rather than merely underpowered.
#'
#' @param columns Numeric columns forming one missingness family.
#' @param reference Always-observed columns the family's absence is tested
#'   against. Without them the test has nothing to compare.
#' @param n_sub Row subsample. The statistic is chi-squared on a large degrees
#'   of freedom, so at 100,000 rows it rejects on structure too small to model.
mcar_test_family <- function(win, columns, reference = character(0),
                             n_sub = 5000L, seed = 0L) {
  columns <- intersect(columns, names(win$train))
  numeric_cols <- columns[vapply(columns, function(f) is.numeric(win$train[[f]]), logical(1))]
  if (!length(numeric_cols)) {
    return(list(statistic = NA_real_, p_value = NA_real_, df = NA_integer_,
                patterns = NA_integer_, note = "no numeric columns in the family"))
  }
  if (!length(reference)) {
    return(list(statistic = NA_real_, p_value = NA_real_, df = NA_integer_,
                patterns = NA_integer_, note = "no always-observed reference columns"))
  }

  set.seed(seed)
  idx <- sample.int(nrow(win$train), min(n_sub, nrow(win$train)))
  # A few family members are enough to define the pattern -- they share a null
  # count by construction -- and keeping all fifty would push the degrees of
  # freedom past the rows again.
  probe <- utils::head(numeric_cols, 3L)
  frame <- as.data.frame(win$train[idx, ..probe])
  frame <- cbind(frame, as.data.frame(win$train[idx, ..reference]))
  frame <- frame[, vapply(frame, function(c) stats::var(c, na.rm = TRUE) > 0, logical(1)),
                 drop = FALSE]

  if (ncol(frame) < 2L) {
    return(list(statistic = NA_real_, p_value = NA_real_, df = NA_integer_,
                patterns = NA_integer_, note = "not enough varying columns"))
  }

  out <- try(suppressWarnings(naniar::mcar_test(frame)), silent = TRUE)
  if (inherits(out, "try-error")) {
    return(list(statistic = NA_real_, p_value = NA_real_, df = NA_integer_,
                patterns = NA_integer_, note = "test not estimable"))
  }
  list(statistic = out$statistic, p_value = out$p.value, df = out$df,
       patterns = out$missing.patterns, note = "")
}

#' Group columns by their exact null count.
#'
#' Columns generated by the same upstream step appear and disappear together, so
#' an identical null count is strong evidence of a shared origin. This is the
#' same grouping the pinned V-block partition encodes, derived here from the
#' data rather than inherited, which makes it a check on that partition as well.
missingness_families <- function(win, features = NULL, min_size = 2L) {
  features <- features %||% win$features
  counts <- vapply(features, function(f) sum(is.na(win$train[[f]])), numeric(1))
  counts <- counts[counts > 0]
  families <- split(names(counts), counts)
  families <- families[lengths(families) >= min_size]
  families[order(-lengths(families))]
}

#' Test every missingness family, and measure whether absence predicts fraud.
#'
#' The MCAR test says the absences have structure. Whether that structure is
#' *useful* is a different question and it is answered next to it: the AUC of
#' the missingness indicator alone against the label. A family that fails MCAR
#' and whose indicator separates fraud is one where imputing would destroy
#' information the model should have.
missingness_scan <- function(win, features = NULL, n_sub = 5000L, verbose = TRUE) {
  families <- missingness_families(win, features)
  y <- as.integer(win$train[[win$label]])
  reference <- reference_columns(win, features)

  rows <- lapply(seq_along(families), function(i) {
    members <- families[[i]]
    test <- mcar_test_family(win, members, reference = setdiff(reference, members),
                             n_sub = n_sub, seed = i)
    indicator <- as.integer(is.na(win$train[[members[[1]]]]))
    auc <- auc_ci_delong(indicator, y)

    if (verbose && i %% 5L == 0L) message(sprintf("  %d/%d", i, length(families)))
    data.table::data.table(
      family = names(families)[[i]], size = length(members),
      null_count = as.numeric(names(families)[[i]]),
      null_share = as.numeric(names(families)[[i]]) / nrow(win$train),
      mcar_statistic = test$statistic, mcar_p = test$p_value,
      mcar_df = test$df, patterns = test$patterns,
      indicator_auc = auc$auc, indicator_auc_lo = auc$lower, indicator_auc_hi = auc$upper,
      example = members[[1]], note = test$note
    )
  })

  out <- data.table::rbindlist(rows)
  out[, mcar_p_bh := adjust_bh(mcar_p)]
  # Absence is informative when it both has structure and separates the label.
  out[, absence_is_signal := !is.na(mcar_p_bh) & mcar_p_bh < 0.05 &
        !is.na(indicator_auc_lo) & (indicator_auc_lo > 0.5 | indicator_auc_hi < 0.5)]
  data.table::setorder(out, -size)
  out[]
}
